// AUTO-GENERATED from src/Renderer/FrameUBO.hpp — do not edit by hand.
// Regenerated by cmake/GenerateFrameUboGlsl.cmake

layout(set = 0, binding = 0) uniform FrameUBO {
    mat4 view;
    mat4 projection;
    mat4 cascadeMatrix0;
    mat4 cascadeMatrix1;
    mat4 cascadeMatrix2;
    vec4 viewPos;
    vec4 lightDirection;
    vec4 fogColor;
    vec4 fogParams; // start, end, density, heightFalloff
    vec4 lightParams; // ambient, diffuse, lightLevels, colorBoost
    vec4 visualParams; // saturation, contrast, colorBoost, unused
    vec4 sunDir;
    vec4 moonDir;
    vec4 skyParams; // time, day, sunset, night
    vec4 cascadeSplits; // xyz ends, w = count
    vec4 moonAmbient; // rgb + strength
    vec4 lightingParams; // blockLightScale, emissiveScale, fogBaseY, underwater
    vec4 waterParams; // wave, refraction, specular, foam
} frame;
