// AUTO-GENERATED from src/Renderer/FrameUBO.hpp — do not edit by hand.
// Regenerated by cmake/GenerateFrameUboGlsl.cmake

layout(set = 0, binding = 0) uniform FrameUBO {
    mat4 view;
    mat4 projection;
    mat4 cascadeMatrix0;
    mat4 cascadeMatrix1;
    mat4 cascadeMatrix2;
    vec4 viewPos;
    vec4 lightDirection;
    vec4 fogColor;
    vec4 fogParams; // start, end, density, heightFalloff
    vec4 lightParams; // ambient, diffuse, reserved (was dead "lightLevels", issue #161), colorBoost
    vec4 visualParams; // material saturation, contrast, reserved (was duplicate colorBoost, issue #161), shadowDebug
    vec4 sunDir;
    vec4 moonDir;
    vec4 skyParams; // time, day, sunset, night
    vec4 cascadeSplits; // xyz ends, w = count
    vec4 moonAmbient; // rgb + strength
    vec4 lightingParams; // blockLightScale, emissiveScale, fogBaseY, underwater
    vec4 waterParams; // wave, refraction, specular, foam
    vec4 cascadeBiasScales; // xyz = normalized-depth units per world texel (worldUnitsPerTexel/depthSpan), w = map resolution
    vec4 cascadeTexelWorldSizes; // xyz = world units per texel XY per cascade (debug density), w unused
    vec4 cascadeGridOffsets01; // xy = cascade0 absolute grid offset, zw = cascade1 (ints as floats)
    vec4 cascadeGridOffsets2; // xy = cascade2 absolute grid offset, zw unused
    vec4 waterQuality; // SSR steps, range, view thickness, directional shadows
    vec4 waterSurfaceParams; // roughness, debug view (0 off/1 normal/2 optical dist/3 fresnel/4 SSR confidence), reserved, reserved
} frame;
