# Generate frame_ubo.inc.glsl from FrameUBO.hpp field list.
# Invoked at build time. Single C++ contract → GLSL layout.

if(NOT FT_VOX_FRAME_UBO_HPP OR NOT FT_VOX_FRAME_UBO_GLSL_OUT)
  message(FATAL_ERROR "GenerateFrameUboGlsl: FT_VOX_FRAME_UBO_HPP and FT_VOX_FRAME_UBO_GLSL_OUT required")
endif()

file(STRINGS "${FT_VOX_FRAME_UBO_HPP}" _lines)

set(_in_struct FALSE)
set(_glsl "// AUTO-GENERATED from src/Renderer/FrameUBO.hpp — do not edit by hand.\n")
string(APPEND _glsl "// Regenerated by cmake/GenerateFrameUboGlsl.cmake\n\n")
string(APPEND _glsl "layout(set = 0, binding = 0) uniform FrameUBO {\n")

set(_field_count 0)
foreach(_line IN LISTS _lines)
  if(NOT _in_struct)
    if(_line MATCHES "struct[ \t]+FrameUBO")
      set(_in_struct TRUE)
    endif()
    continue()
  endif()
  # End of struct
  if(_line MATCHES "^[ \t]*\\};")
    break()
  endif()
  # glm::mat4 name;  or glm::vec4 name;  with optional // comment
  if(_line MATCHES "glm::(mat4|vec4)[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
    set(_ty "${CMAKE_MATCH_1}")
    set(_nm "${CMAKE_MATCH_2}")
    set(_cmt "")
    if(_line MATCHES "//[ \t]*(.*)$")
      string(STRIP "${CMAKE_MATCH_1}" _cmt)
      if(NOT _cmt STREQUAL "")
        set(_cmt " // ${_cmt}")
      endif()
    endif()
    string(APPEND _glsl "    ${_ty} ${_nm};${_cmt}\n")
    math(EXPR _field_count "${_field_count} + 1")
  endif()
endforeach()

string(APPEND _glsl "} frame;\n")

if(_field_count LESS 10)
  message(FATAL_ERROR "GenerateFrameUboGlsl: too few fields parsed (${_field_count}) from ${FT_VOX_FRAME_UBO_HPP}")
endif()

get_filename_component(_outdir "${FT_VOX_FRAME_UBO_GLSL_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_outdir}")
file(WRITE "${FT_VOX_FRAME_UBO_GLSL_OUT}" "${_glsl}")
message(STATUS "FrameUBO GLSL: wrote ${FT_VOX_FRAME_UBO_GLSL_OUT} (${_field_count} fields)")
