# Writes generated/BuildInfo.inc with git revision metadata.
# Invoked at build time so the hash tracks the tree used to compile.

if(NOT DEFINED FT_VOX_SOURCE_DIR OR NOT DEFINED FT_VOX_BUILD_INFO_OUT)
  message(FATAL_ERROR "GenerateBuildInfo.cmake requires FT_VOX_SOURCE_DIR and FT_VOX_BUILD_INFO_OUT")
endif()

set(GIT_HASH "unknown")
set(GIT_BRANCH "unknown")
set(GIT_DIRTY "0")
set(GIT_DESCRIBE "unknown")

find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${FT_VOX_SOURCE_DIR}/.git")
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${FT_VOX_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY "${FT_VOX_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND ${GIT_EXECUTABLE} status --porcelain
    WORKING_DIRECTORY "${FT_VOX_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  if(NOT GIT_STATUS STREQUAL "")
    set(GIT_DIRTY "1")
  endif()
  execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --always --tags --dirty
    WORKING_DIRECTORY "${FT_VOX_SOURCE_DIR}"
    OUTPUT_VARIABLE GIT_DESCRIBE
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
endif()

if(GIT_HASH STREQUAL "")
  set(GIT_HASH "unknown")
endif()
if(GIT_BRANCH STREQUAL "")
  set(GIT_BRANCH "unknown")
endif()
if(GIT_DESCRIBE STREQUAL "")
  set(GIT_DESCRIBE "${GIT_HASH}")
endif()

string(TIMESTAMP BUILD_UTC "%Y-%m-%dT%H:%M:%SZ" UTC)

# Escape for C string literals
foreach(var GIT_HASH GIT_BRANCH GIT_DESCRIBE BUILD_UTC)
  string(REPLACE "\\" "\\\\" ${var} "${${var}}")
  string(REPLACE "\"" "\\\"" ${var} "${${var}}")
endforeach()

get_filename_component(_outdir "${FT_VOX_BUILD_INFO_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_outdir}")

file(WRITE "${FT_VOX_BUILD_INFO_OUT}"
"// Auto-generated by cmake/GenerateBuildInfo.cmake — do not edit.
#pragma once

#define FT_VOX_GIT_HASH \"${GIT_HASH}\"
#define FT_VOX_GIT_BRANCH \"${GIT_BRANCH}\"
#define FT_VOX_GIT_DIRTY ${GIT_DIRTY}
#define FT_VOX_GIT_DESCRIBE \"${GIT_DESCRIBE}\"
#define FT_VOX_BUILD_UTC \"${BUILD_UTC}\"
")
